version: '3.8'

services:
  managarr-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: managarr-dev
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/frontend/node_modules
      - /app/backend/node_modules
      - ./config:/app/config
      - ./data:/app/data
      - /path/to/your/media:/media:ro  # Update this path
    environment:
      - NODE_ENV=development
      - FRONTEND_PORT=3000
      - BACKEND_PORT=5000
      - CONFIG_PATH=/app/config
      - DATA_PATH=/app/data
      - USE_SQLITE=true
      - SQLITE_PATH=/app/data/managarr.db
    networks:
      - managarr-dev
    restart: unless-stopped

networks:
  managarr-dev:
    driver: bridge

volumes:
  managarr_data:
    driver: local
